version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=6wbm34lm0l-=$$bf@2)2padz0485rt6=)9s!5cahn(ay9hw2b_1
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_AyV9vbFkUECmHIZy7vxpsG4y00Zu5U6Ndo
      - STRIPE_TEST_SECRET_KEY=sk_test_9sHzBcL3tkSorTdNmHQBUars00FPVN6CfN
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
