# Generated by Django 2.2.7 on 2019-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
