# Generated by Django 2.2.7 on 2019-12-15 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('special_status', 'Can see all items')]},
        ),
    ]
