# Generated by Django 2.2.7 on 2019-12-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20191215_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
