# Generated by Django 2.2.7 on 2019-12-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191216_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('special_status', 'Can view all items')]},
        ),
    ]
