# Generated by Django 2.2.7 on 2019-12-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20191216_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('special_status', 'Can order all items')]},
        ),
    ]
