# Generated by Django 2.2.7 on 2019-12-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20191216_0159'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
